<?php

$labels['settingslist'] = 'Пароли приложений';
$labels['settingstitle'] = 'Пароли приложений';

$labels['popup_expire_soon'] = 'Срок действия некоторых паролей приложений скоро истечет. Пожалуйста, проверьте это через «Настройки» -> "Пароли приложений".';
$labels['popup_format_save_error'] = 'Ошибка при сохранении пароля: формат не соответствует требованиям.';
$labels['popup_generic_save_error'] = 'Ошибка при сохранении пароля.';
$labels['popup_duplicate_save_error'] = 'Ошибка при сохранении пароля: не используйте повторно имена приложений.';
$labels['popup_successful_deletion'] = 'Запись успешно удалена.';
$labels['missingapplicationname'] = 'Введите допустимое имя приложения.';

$labels['application'] = 'Приложение';
$labels['creation_date'] = 'Создан в';
$labels['expiry_date']   = 'Срок действия истекает';
$labels['created'] = 'Создан';
$labels['remove'] = 'Удалить';

$labels['name_field'] = 'Название:';
$labels['create_password'] = 'Сгенерировать пароль';
$labels['new_application_description'] = 'Создайте отдельный пароль для каждого приложения (например, "My_Android", "mutt_office", ...).';
$labels['only_delete_one_password'] = 'Цель заключается в том, чтобы в случае потери устройства вам нужно было удалить только пароль для этого устройства.';
$labels['only_valid_characters'] = 'Вы можете использовать только следующие символы:';
// this will be used in the placeholder of the input field, eg. "only use a-zA-Z0-9"
$labels['only_use'] = 'используйте только';

$labels['new_application_ready'] = 'Ваш новый пароль создан для:';
$labels['new_application_copy']  = 'Вы можете нажать на имя пользователя и пароль, чтобы скопировать их.';
$labels['new_application_once']  = 'Пароль отображается только один раз.';
$labels['please_use_username']   = 'Пожалуйста, используйте следующее имя пользователя и пароль для этого приложения.';
$labels['new_username'] = 'Имя пользователя';
$labels['new_password'] = 'Пароль';
